// <auto-generated />
using EdlinkCapstone.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EdlinkCapstone.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20210507052513_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EdlinkCapstone.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("PassWord")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Email = "andy@gmail.com",
                            FirstName = "Andy",
                            LastName = "Cole",
                            PassWord = "andy123"
                        },
                        new
                        {
                            ID = -2,
                            Email = "jason@gmail.com",
                            FirstName = "Jason",
                            LastName = "Kenny",
                            PassWord = "jason123"
                        },
                        new
                        {
                            ID = -3,
                            Email = "elizabeth@gmail.com",
                            FirstName = "Elizabeth",
                            LastName = "Notley",
                            PassWord = "elizabeth123"
                        },
                        new
                        {
                            ID = -4,
                            Email = "asu@gmail.com",
                            FirstName = "Asu",
                            LastName = "Ben",
                            PassWord = "asu123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
